services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    labels:
      - "traefik.enable=true"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.example.com`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  plex:
    image: linuxserver/plex
    container_name: plex
    labels:
      - "traefik.enable=true"
    network_mode: host
    environment:
      - VERSION=docker
    restart: always
    volumes:
      - ./plex:/etc/plex
  minecraft:
    image: itzg/minecraft-server
    labels:
      - "traefik.enable=true"
    ports:
      - "25565:25565"
    volumes:
      - "~/minecraft_data:/data"
  reverse-proxy:
    image: traefik:v3.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
volumes:
  prom_data: