services:

  reverse-proxy:
    image: traefik:v3.3
    container_name: traefik
    command:
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --providers.docker=true
      - --api.insecure=true
      #- --certificatesResolvers.myresolver.acme.tlsChallenge=true
      #- --certificatesResolvers.myresolver.acme.email=your-email@example.com
      #- --certificatesResolvers.myresolver.acme.storage=/etc/traefik/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/etc/traefik/acme.json

  whoami:
    image: traefik/whoami
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entryPoints=web"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    labels:
      - "traefik.enable=true"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.example.com`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  plex:
    image: linuxserver/plex
    container_name: plex
    labels:
      - "traefik.enable=true"
    network_mode: host
    environment:
      - VERSION=docker
    restart: always
    volumes:
      - ./plex:/etc/plex
  minecraft:
    image: itzg/minecraft-server
    labels:
      - "traefik.enable=true"
    ports:
      - "25565:25565"
    volumes:
      - "~/minecraft_data:/data"
volumes:
  prom_data: