name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:                    # Updated job name for clarity
    name: Linting Job
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Lint Dockerfile using Hadolint
      - name: Lint Dockerfile with Hadolint
        uses: docker://hadolint/hadolint:latest
        with:
          args: < ${{ env.DOCKERFILE_PATH }}
env:
  DOCKERFILE_PATH: Dockerfile      # Extracted Dockerfile path as an environment variable
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    needs: lint                       # Wait for 'lint' stage to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Build
        run: |
          echo "Building application"
          docker-compose up --build -d
  test:
    name: Test Stage
    runs-on: ubuntu-latest
    needs: build                      # Wait for 'build' stage to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo "Running tests"
          # Replace with actual test commands

  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: test                       # Wait for 'test' stage to complete
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying application"
          # Add deployment commands here