name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint Dockerfile with Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code            # Checkout the repository
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: docker://hadolint/hadolint:latest
        with:
          args: < Dockerfile           # Run Hadolint on your Dockerfile

  build:
    name: Build Stage
    runs-on: ubuntu-latest
    needs: lint                       # Wait for 'lint' stage to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Build
        run: |
          echo "Building application"
          docker-compose up --build -d
  test:
    name: Test Stage
    runs-on: ubuntu-latest
    needs: build                      # Wait for 'build' stage to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo "Running tests"
          # Replace with actual test commands

  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: test                       # Wait for 'test' stage to complete
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying application"
          # Add deployment commands here